<a href="https://colab.research.google.com/github/Anand1923/DSA_Assignments/blob/main/Case_Study_10_Probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/mushrooms.csv')

In [4]:
data

class cap-shape cap-surface  ... spore-print-color population habitat
0        p         x           s  ...                 k          s       u
1        e         x           s  ...                 n          n       g
2        e         b           s  ...                 n          n       m
3        p         x           y  ...                 k          s       u
4        e         x           s  ...                 n          a       g
...    ...       ...         ...  ...               ...        ...     ...
8119     e         k           s  ...                 b          c       l
8120     e         x           s  ...                 b          v       l
8121     e         f           s  ...                 b          c       l
8122     p         k           y  ...                 w          v       l
8123     e         x           s  ...                 o          c       l

[8124 rows x 23 columns]

In [ ]:
data.describe()

class cap-shape cap-surface  ... spore-print-color population habitat
count   8124      8124        8124  ...              8124       8124    8124
unique     2         6           4  ...                 9          6       7
top        e         x           y  ...                 w          v       d
freq    4208      3656        3244  ...              2388       4040    3148

[4 rows x 23 columns]

Checking null values

In [5]:
data.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

Splitting data into feature and class set

In [6]:
x=data.drop('class',axis=1)
y=data['class']

In [7]:
x=pd.get_dummies(x)

In [ ]:
y=pd.get_dummies(y)

Splitting data into training  and test set

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

Feature scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[-0.23814231, -0.02219484,  1.25162068, ..., -0.40181631,
        -0.21906076, -0.16049167],
       [-0.23814231, -0.02219484, -0.7989641 , ..., -0.40181631,
        -0.21906076, -0.16049167],
       [-0.23814231, -0.02219484,  1.25162068, ..., -0.40181631,
        -0.21906076, -0.16049167],
       ...,
       [-0.23814231, -0.02219484, -0.7989641 , ..., -0.40181631,
        -0.21906076, -0.16049167],
       [-0.23814231, -0.02219484,  1.25162068, ..., -0.40181631,
        -0.21906076, -0.16049167],
       [-0.23814231, -0.02219484, -0.7989641 , ..., -0.40181631,
        -0.21906076, -0.16049167]])

In [10]:
y_train

5832    p
601     e
1601    e
4941    p
7492    p
       ..
4931    e
3264    p
1653    e
2607    e
2732    e
Name: class, Length: 6093, dtype: object

#1.Naive Bayes Classification

Fitting Gaussian Naive Bayes to training set

In [11]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

Prediction of test resut

In [12]:
y_pred=classifier.predict(x_test)

Making confusion matrix to chck accuracy

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
accuracy_score(y_test,y_pred)

0.9556868537666174

In [32]:
cm

array([[1061,    0],
       [   0,  970]])

There is no *misclassification*

#2 DECISION TREE CLASSIFICATION

In [15]:
# Decision Tree Classification
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [22]:
y_pred = dt.predict(x_test)



In [21]:
dt.score(x_test, y_test)

1.0

Accuracy is 100%

In [24]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[1061,    0],
       [   0,  970]])

`There is no *misclassification*`

#3. Logistic Regression Classification


In [30]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test)


In [28]:
lr.score(x_test, y_test)

1.0

In [31]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[1061,    0],
       [   0,  970]])

There is no *misclassification* 

# 4 Random Forest Classification

In [36]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

1.0

In [37]:
y_pred = rf.predict(x_test)

In [39]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[1061,    0],
       [   0,  970]])

Conclusion

Most of the models are predicting results with high accuracy.
Hence we can confirm that mushrooms are safe to eat.

There is no *misclassification* 